### ISSUE TITLE
crashes on example given in pypi index page

### ISSUE THREAD

**Issue by vonj** [kennethreitz/pyandoc#10]
In [2]: import pandoc

In [3]: doc = pandoc.Document()

In [4]: doc.markdown = '''
# I am an H1 Tag
* bullet point
* more points
* point with [link](http://kennethreitz.com)!
'''

In [5]: print doc.rst
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-61aa934977c6> in <module>()
----> 1 print doc.rst

/usr/local/lib/python2.7/dist-packages/pandoc/core.pyc in <lambda>(x, fmt)
     33                         clean_fmt = fmt.replace('+', '_')
     34 			setattr(cls, clean_fmt, property(
---> 35                                 (lambda x, fmt=fmt: cls._output(x, fmt)), # fget
     36 				(lambda x, y, fmt=fmt: cls._input(x, y, fmt)))) # fset
     37 

/usr/local/lib/python2.7/dist-packages/pandoc/core.pyc in _output(self, format)
     46                         [PANDOC_PATH, '--from=%s' % self._format, '--to=%s' % format],
     47                         stdin=subprocess.PIPE,
---> 48                         stdout=subprocess.PIPE
     49 		)
     50 

/usr/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    709                                 p2cread, p2cwrite,
    710                                 c2pread, c2pwrite,
--> 711                                 errread, errwrite)
    712         except Exception:
    713             # Preserve original exception in case os.close raises.

/usr/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1306                         raise
   1307                 child_exception = pickle.loads(data)
-> 1308                 raise child_exception
   1309 
   1310 

OSError: [Errno 2] No such file or directory

In [6]:

**Comment by lmichelbacher** [comment]
This is probably because `pandoc.PANDOC_PATH` isn’t set. This means your local pandoc binary cannot be found.

**Comment by kennethreitz** [comment]
This should now be fixed :)
