### ISSUE TITLE
Incorrect info in readme

### ISSUE THREAD

**Issue by hedleyroos** [kennethreitz/pyandoc#15]
The readme says `pandoc.PANDOC_PATH = '/usr/bin/pandoc'` but it should be `pandoc.core.PANDOC_PATH = '/usr/bin/pandoc'`.

**Comment by andresmrm** [comment]
`pandoc.PANDOC_PATH = '/usr/bin/pandoc'`
Didn't worked here, but
`pandoc.core.PANDOC_PATH = '/usr/bin/pandoc'`
yes.
So I confirm the error on Python2. (Thanks for the tip @hedleyroos )

**Comment by msabramo** [comment]
You should just use [pypandoc](https://github.com/bebraw/pypandoc), as this project looks to no longer be maintained.

**Comment by andresmrm** [comment]
Good point...

**Comment by kennethreitz** [comment]
@msabramo I hadn't seen this one, thanks!
