### ISSUE TITLE
Python 3 uses unicode, and is not compatible with subprocess pipes

### ISSUE THREAD

**Issue by Brianetta** [kennethreitz/pyandoc#2]
I'm using pyandoc inside a Python 3 CGI script.  I'm having to convert strings in the following manner to avoid getting an exception from Python:

    doc.markdown = "This is a *really* simple example".encode('latin-1')

    print(doc.html.decode('UTF-8'))

Failure to do this causes some messy (and difficult to understand) errors and an aborted script.  Perhaps this should be handled explicitly, or at least caught and explained?

**Comment by kennethreitz** [comment]
You have to pass in byte strings in Python 3.
