### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by Alquimista** [kennethreitz/pyandoc#5]
file "c:\users\calcon\desktop\src\pyandoc\pandoc\core.py", line 35, in <lambda>
(lambda x, fmt=fmt: cls._output(x, fmt)), # fget
  File "c:\users\calcon\desktop\src\pyandoc\pandoc\core.py", line 48, in _output
    stdout=subprocess.PIPE
  File "C:\Python27\lib\subprocess.py", line 679, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 896, in _execute_child
    startupinfo)
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado

**Comment by kennethreitz** [comment]
This should now be fixed!

**Comment by AnshumanMisra007** [comment]
# Build mongoimport command
collection = OSM_FILE[:OSM_FILE.find('.')]
working_directory = '/Users/Anshuman Misra/Downloads/'
json_file = OSM_FILE + '.json'

mongoimport_cmd = 'mongoimport -h 127.0.0.1:27017 ' + \
                  '--db ' + db_name + \
                  ' --collection ' + collection + \
                  ' --file ' + working_directory + json_file

# Before importing, drop collection if it exists (i.e. a re-run)
if collection in db.collection_names():
    print 'Dropping collection: ' + collection
    db[collection].drop()

# Execute the command
print 'Executing: ' + mongoimport_cmd
subprocess.call(mongoimport_cmd.split())
on running this 
WindowsErrorTraceback (most recent call last)
<ipython-input-67-979523e02116> in <module>()
     13 # Execute the command
     14 print 'Executing: ' + mongoimport_cmd
---> 15 subprocess.call(mongoimport_cmd.split())

C:\Users\Anshuman Misra\Downloads\Anaconda2\lib\subprocess.pyc in call(*popenargs, **kwargs)
    166     retcode = call(["ls", "-l"])
    167     """
--> 168     return Popen(*popenargs, **kwargs).wait()
    169 
    170 

C:\Users\Anshuman Misra\Downloads\Anaconda2\lib\subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    388                                 p2cread, p2cwrite,
    389                                 c2pread, c2pwrite,
--> 390                                 errread, errwrite)
    391         except Exception:
    392             # Preserve original exception in case os.close raises.

C:\Users\Anshuman Misra\Downloads\Anaconda2\lib\subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
    638                                          env,
    639                                          cwd,
--> 640                                          startupinfo)
    641             except pywintypes.error, e:
    642                 # Translate pywintypes.error to WindowsError, which is

WindowsError: [Error 2] The system cannot find the file specified
